// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcxedciqvragvaofsshg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjeGVkY2lxdnJhZ3Zhb2Zzc2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTIwODQsImV4cCI6MjA1NDA4ODA4NH0.ShMcbaxtwisxrXor5_zbHkvBMhNx4l_EDJ8iA2_3adU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);